# Gitpod Configuration for Geekout Vegas 2026
# Prebuild handles all dependencies - cached for all attendees

image: gitpod/workspace-full:latest

# Prebuild: runs once when you push, cached for all attendees
tasks:
  - name: Ready
    init: |
      # Install npm dependencies
      npm install

      # Install Playwright browser
      npx playwright install chromium

      # Install Claude Code CLI
      npm install -g @anthropic-ai/claude-code

      # Pre-install Claude Code plugins (marketplace + frontend-design)
      mkdir -p ~/.claude/plugins/marketplaces
      git clone https://github.com/anthropics/claude-code-plugins.git ~/.claude/plugins/marketplaces/claude-code-plugins || true
      claude plugin install frontend-design@claude-code-plugins || true

      # Warm up caches: compile TypeScript, create dirs, warm Playwright, create demo
      npm run prebuild

      # Pre-compile ts-node cache for instant startup
      npx ts-node --transpileOnly -e "console.log('TypeScript ready')"

      echo "Prebuild complete!"

    command: |
      echo ""
      echo "=========================================="
      echo "  GEEKOUT VEGAS 2026 - Ready to Code!"
      echo "=========================================="
      echo ""
      echo "1. export ANTHROPIC_API_KEY=your_key"
      echo "2. export GEMINI_API_KEY=your_key"
      echo "3. Type: claude"
      echo ""

# PORTS: When your app listens on these ports, they auto-forward to PUBLIC URLs
ports:
  - port: 3000
    onOpen: open-preview
    visibility: public
  - port: 3001
    onOpen: notify
    visibility: public
  - port: 4000
    onOpen: notify
    visibility: public
  - port: 5000
    onOpen: notify
    visibility: public
  - port: 5173
    onOpen: open-preview
    visibility: public
  - port: 8000
    onOpen: notify
    visibility: public
  - port: 8080
    onOpen: open-preview
    visibility: public
  - port: 8081
    onOpen: notify
    visibility: public

github:
  prebuilds:
    main: true
    branches: true
    pullRequests: true
    addCheck: true

vscode:
  extensions:
    - esbenp.prettier-vscode
    - formulahendry.auto-rename-tag
    - bradlc.vscode-tailwindcss
    - christian-kohler.path-intellisense
    - pkief.material-icon-theme
